dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
dist/mobx-async-store.umd.js
package.json
spec/Model.spec.js
src/Model.js
src/utils.js

Model#dirtyAttributes

---

spec/Model.spec.js
spec/fixtures/exampleRelationalResponses.js
src/Store.js
src/decorators/relationships.js

Currently, if a JSON response includes a relationship to an unknown type, say "sub_stages", the Store throws an "Could not find a collection for type 'sub_stages'".
In order to make it easier to do changes in the backend without breaking existing clients, the Store should just ignore any types it does not recognize.
We leave the exception checking in the code because it's useful in other scenarios, but avoid calling `getRecord` when we know it will fail.

Ignore unexpected relations in JSON response

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
package.json
spec/Model.spec.js
src/Model.js
src/ObjectPromiseProxy.js
src/decorators/relationships.js

1. ~Do we _need_ `isDirty` to be `true` is _any_ change is made on a relationship? What does that mean for long-living objects that are related to many others? Should those objects be dirty if any related object is dirty?~
2. Can we put the burden of checking for dirty relationships on the caller? So as to avoid potentially walking the entire object graph every time a caller asks for dirty state.
* We can do this at write time since we have access to the methods that make these mutations. We do this by introducing a new `Model#_dirtyRelationships` Set which keeps a set of paths that have changed since the last snapshot.
I would still like to refactor the `Model#dirtyAttributes` implementation to track state at write time, but in the meantime, at least saves us _some_ work by removing the …

derive Model#isDirty from Model#dirtyAttributes

---

spec/Model.spec.js
src/Model.js

closing a model means doing a deep clone of its attributes, but _not_ of its relationships. relationships are still references to their original targets.

define Model#clone

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
package.json
spec/Model.spec.js
src/decorators/relationships.js

when removing a relatedRecord, if it was not found it would remove the
relationship for the last record (at index -1). This had the side effect
of removing two records when one was found because of the recursive
nature between `remove` and `setRelatedRecord`.
PR to pull it into artemis-store: https://github.com/artemis-ag/artemis-store/pull/54
PR to pull it into portal: https://github.com/artemis-ag/portal/pull/3206

guard against removing extra related records

---

.eslintrc.js
package.json
spec/Store.spec.js
src/decorators/relationships.js

aliased @relatedToOne property fails to discern type

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
package.json
spec/Model.spec.js
src/ObjectPromiseProxy.js

I came across an issue where if the an id attribute is not defined in a serializer (which it shouldn't be anyway) newly persisted records are not overriding their tmp ids with the id returned from the server. We should be using the data id across the board.

Fix issue with attr id over data id

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
package.json
spec/Model.spec.js
src/ObjectPromiseProxy.js

add raw server errors to the Model errors so that server validations can be accessed. We will figure out a better way to align to the format of the server validations and the client validations but that will require a much deeper dive, scheduled for the end of March 2020.

dump all errors for somewhat better parsing

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
package.json
spec/Model.spec.js
src/Model.js
src/ObjectPromiseProxy.js
src/Store.js
src/utils.js

At one point a snapshot only happened alongside saving a record, so we could use the last snapshot as a "source of truth" for determining if a record was dirty or not. Recently, we have introduced the idea of taking snapshots at various points as "rollback targets" without persisting these snapshots to the api. So we now need to distinguish between a record being "dirty" (changes made since last snapshot) and a record being "persisted" (having unsaved changes). 
We introduced ~`isPersisted`~ `hasUnpersistedChanges` to be that extra flag. ~As I'm typing this out, I'm realizing that `isPersisted` is probably a bad name. Technically, a record is referred to as "persisted" if it _has ever been_ persisted. Maybe we should rename `isPersisted` to something like `hasUnpersistedChanges`? Idk. I …

Rollback to persisted

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
package.json
spec/Model.spec.js
src/Model.js

`Model#attributes` used to exclude falsey values like `0`, `''`, `false` and assume they meant `undefined` or `null` so we couldn't snapshot any properties which had those values—they just became `undefined`. this fixes that.
we might want to allow `null` at some point, but i guess we haven't needed it yet, so i'm going to go ahead and continue to exclude it.

Fix falsey value snapshots

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
package.json
spec/Model.spec.js
src/Model.js

quick bugfix to allow saving undefined relationships. we got a little overzealous in our invariant checking in #40

Check undefined rel

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
package.json
spec/Model.spec.js
src/Model.js

The validation step was failing for a model that does not have relationships defined.

Fix validation error when no relationships are defined

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
package.json
spec/Model.spec.js
spec/Store.spec.js
src/ObjectPromiseProxy.js
src/Store.js

We moved the `records` and `cache` attributes on the main `Store#data` observable object. This allows us to use the set, get, and delete methods. The impetus for this was to get the performance of `Store#remove` down to `O(1)` instead `O(n)`.
So, records and cache are read and written to like so.
```JavaScript
this.data[type].records[id] = record
// becomes
this.data[type.records.set(String(id), record)
this.data[type].records[id]
// becomes
this.data[type].records.get(id)
// and we can delete records simply
this.data[type].records.delete(id)
```

Fix store delete method

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
docs/classes/Model.html
docs/classes/RelatedRecordsArray.html
docs/classes/Schema.html
docs/classes/Store.html
docs/data.json
docs/files/src_Model.js.html
docs/files/src_Store.js.html
docs/files/src_decorators_attributes.js.html
docs/files/src_decorators_relationships.js.html
docs/files/src_schema.js.html
docs/files/src_utils.js.html
docs/index.html
package.json
spec/Model.spec.js
src/Model.js
src/Store.js
src/decorators/attributes.js
src/utils.js

`moment` is enormous, and we don't use it for anything useful in here, so let's say goodbye.
while doing this i found a bunch of fns duplicted in `src/Model.js` and in `src/decorators/attribute.js`. I can't find anyone importing `attribute` from `src/Model`, so I went ahead and deleted it.

Remove moment

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
docs/classes/Model.html
docs/classes/RelatedRecordsArray.html
docs/classes/Schema.html
docs/classes/Store.html
docs/data.json
docs/files/src_Model.js.html
docs/files/src_Store.js.html
docs/files/src_decorators_attributes.js.html
docs/files/src_decorators_relationships.js.html
docs/files/src_schema.js.html
docs/files/src_utils.js.html
docs/index.html
package.json
spec/Model.spec.js
src/Model.js

* Define `Model#isEqual`
* Define `Model#isSame`
* fix bug in `Model#clone` where relationships were aliased

Model instance equality methods

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
docs/classes/Model.html
docs/classes/RelatedRecordsArray.html
docs/classes/Schema.html
docs/classes/Store.html
docs/data.json
docs/files/src_Model.js.html
docs/files/src_Store.js.html
docs/files/src_decorators_attributes.js.html
docs/files/src_decorators_relationships.js.html
docs/files/src_schema.js.html
docs/files/src_utils.js.html
docs/index.html
package.json
rollup.config.js
spec/QueryString.spec.js
src/QueryString.js
src/main.js
src/utils.js
yarn.lock

just to illustrate that behavior is not changing, here's a snippet of a session in a node console:
```
> params
{ fields: { articles: [ 'title', 'body' ], people: 'name' } }
> decodeURI(jqueryParam(params))
'fields[articles][]=title&fields[articles][]=body&fields[people]=name'
> decodeURI(qs.stringify(params, { arrayFormat: 'brackets' }))
'fields[articles][]=title&fields[articles][]=body&fields[people]=name'
```
I considered using `query-string`, since it's much smaller, but this didn't instill confidence:
```
> queryString.stringify(params, { arrayFormat: 'bracket' })
'fields=%5Bobject%20Object%5D'
```

Replace jquery-param with qs

---

README.md
dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
docs/classes/Model.html
docs/classes/RelatedRecordsArray.html
docs/classes/Schema.html
docs/classes/Store.html
docs/data.json
docs/files/src_Model.js.html
docs/files/src_Store.js.html
docs/files/src_decorators_attributes.js.html
docs/files/src_decorators_relationships.js.html
docs/files/src_schema.js.html
docs/files/src_utils.js.html
docs/index.html
package.json
spec/Store.spec.js
src/Store.js

* define `Store#build` to build a model instance w/o adding it to the store
sometimes we want to be able to create an ephemeral model instance w/o adding it to the store (building a model instance from form data for example) this instance may or may not get added to the store later, but it's nice to not have to explicitly remove the record from the store if, for example, the form is abandoned.

Store#build

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
docs/classes/Model.html
docs/classes/RelatedRecordsArray.html
docs/classes/Schema.html
docs/classes/Store.html
docs/data.json
docs/files/src_Model.js.html
docs/files/src_Store.js.html
docs/files/src_decorators_attributes.js.html
docs/files/src_decorators_relationships.js.html
docs/files/src_schema.js.html
docs/files/src_utils.js.html
docs/index.html
package.json
spec/Store.spec.js
spec/utils.spec.js
src/Store.js
src/utils.js

Querying for many identified records is difficult in `mobx-async-store`. You can use `findOne`, which will kick off a query for each record, or `findAll`, which can cause 414 errors with a long list of ids.
`findMany` treats the syntax like a `findOne` but queries like a `findAll` with `filter[ids]` params. It first looks in the store to find available records, then splits into multiple queries for the records it does not have, avoiding the query max length. It then concatenates the responses with the records from the store and returns all of the records.
This PR is really long, but the relevant changes are in [Store](https://github.com/artemis-ag/mobx-async-store/pull/61/files#diff-7a95c660669a260e384552aaa39be4bfR212-R305) and [utils](https://github.com/artemis-ag/mobx-async-store/pull/6 …

add findMany method to store

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
docs/classes/Model.html
docs/classes/RelatedRecordsArray.html
docs/classes/Schema.html
docs/classes/Store.html
docs/data.json
docs/files/src_Model.js.html
docs/files/src_Store.js.html
docs/files/src_decorators_attributes.js.html
docs/files/src_decorators_relationships.js.html
docs/files/src_schema.js.html
docs/files/src_utils.js.html
docs/index.html
package.json
spec/Store.spec.js
src/Store.js

Right now, if you execute a query twice without a `fromServer` param, the second one returns an array rather than a promise.
```js
store.findAll('todos')
=> returns Promise
store.findAll('todos')
=> returns Array
```
This works with `async/await`, but is not thennable.
```js
store.findAll('todos').then(...) // works
store.findAll('todos').then(...) // blows up
```
This is a potentially breaking change:
- If someone has forgotten to use `fromServer: false` but is expecting an array, it would break.
```js
// with current code
let todos = await store.findAll('todos')
todos.map(() => {}) // works
todos = store.findAll('todos')
todos.map(() => {}) // works
```

return a promise for findAll unless fromServer is explicitly false

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
docs/classes/Model.html
docs/classes/RelatedRecordsArray.html
docs/classes/Schema.html
docs/classes/Store.html
docs/data.json
docs/files/src_Model.js.html
docs/files/src_Store.js.html
docs/files/src_decorators_attributes.js.html
docs/files/src_decorators_relationships.js.html
docs/files/src_schema.js.html
docs/files/src_utils.js.html
docs/index.html
package.json
src/Store.js

Previously, we had been relying on most relationships during `bulkSave()` to be handled in the completion handlers, based on ids passed through the completions' options. Since we actually have to pass `uploaded_documents` through via relationships, we have to pass the relationships through via `options`, which we hadn't previously been using in `bulkSave()`. No test, because it would end up being more of a test of `jsonapi()`'s implementation, which is already tested.

Pass options to jsonapi() in bulkSave for relationships [Ref #173716895]

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
docs/classes/Model.html
docs/classes/RelatedRecordsArray.html
docs/classes/Schema.html
docs/classes/Store.html
docs/data.json
docs/files/src_Model.js.html
docs/files/src_Store.js.html
docs/files/src_decorators_attributes.js.html
docs/files/src_decorators_relationships.js.html
docs/files/src_schema.js.html
docs/files/src_utils.js.html
docs/index.html
package.json
spec/Model.spec.js
spec/Store.spec.js
src/Store.js
src/utils.js

Adds server errors directly to their corresponding attributes in models.
Previously we had made the decision to lump all server errors onto a "server" attribute so that they would at least be accessible. Now, when errors come back from the API we parse the source pointer for each error to determine which attribute the error is for and add it in the same manner as our model validations.
This also support errors for create/update requests using the JSONApi bulk extension. When these errors are returned, the pointer will contain an index that corresponds to the payload of the original request which is used to determine which object in the store the errors should be assigned to.

add server errors to models

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
docs/classes/Model.html
docs/classes/RelatedRecordsArray.html
docs/classes/Schema.html
docs/classes/Store.html
docs/data.json
docs/files/src_Model.js.html
docs/files/src_Store.js.html
docs/files/src_decorators_attributes.js.html
docs/files/src_decorators_relationships.js.html
docs/files/src_schema.js.html
docs/files/src_utils.js.html
docs/index.html
package.json
spec/Model.spec.js
spec/fixtures/exampleRelationalResponses.js
src/decorators/relationships.js

There's a "back door" in mobx-async-store that allows for reciprocal references to be inferred by `_id`. This is idiomatic Ruby on Rails, NOT jsonapi, and should not be supported in mobx-async-store.
It can cause issues if the relationship type doesn't match a model name, if the server returns `meta: { included: false }`.
```js
{
id: "1",
type: "users",
attributes:
{ name: "Jon" }
relationships: {
todos: {
meta: { included: false }
},
awesome_todos: {
meta: { included: false }
}
}
}
// works
user.todos
// breaks
user.awesome_todos
```
https://github.com/artemis-ag/mobx-async-store/pull/69/commits/6979d788d51dfe740e75a1173f7cd90280655639

fix reference by _id

---

.circleci/config.yml
README.md
dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
docs/classes/Model.html
docs/classes/RelatedRecordsArray.html
docs/classes/Schema.html
docs/classes/Store.html
docs/data.json
docs/files/src_Model.js.html
docs/files/src_Store.js.html
docs/files/src_decorators_attributes.js.html
docs/files/src_decorators_relationships.js.html
docs/files/src_schema.js.html
docs/files/src_utils.js.html
docs/index.html
package.json
spec/ExampleApp.js
spec/Model.spec.js
spec/Store.spec.js
src/Store.js
src/decorators/relationships.js

This PR is the first step in moving us away from using `fromServer` options it also removes the ability to specify model classes on relationships.
The only actual change that will need to be made in portal and mobile is that `fetchOne` method signature now takes options (ie `{queryParams: {include: 'todos'}}`) instead of the queryParams directly like it was (ie. `{include: 'todos'}`)
The corresponding PRs are
https://github.com/artemis-ag/portal/pull/4719
https://github.com/artemis-ag/artemis-mobile/pull/345

Deprecate fromServer options & remove ability to specify model class on relationships  176874011

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
docs/classes/Model.html
docs/classes/RelatedRecordsArray.html
docs/classes/Schema.html
docs/classes/Store.html
docs/data.json
docs/files/src_Model.js.html
docs/files/src_Store.js.html
docs/files/src_decorators_attributes.js.html
docs/files/src_decorators_relationships.js.html
docs/files/src_schema.js.html
docs/files/src_utils.js.html
docs/index.html
package.json
spec/Model.spec.js
src/Model.js
src/decorators/relationships.js

Remove the attribute listeners to help with memory bloat - instead we will compare current attributes and relationships to the previous snapshot when checking `isDirty`

Remove attribute listeners 177025210

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
docs/classes/Model.html
docs/classes/RelatedRecordsArray.html
docs/classes/Schema.html
docs/classes/Store.html
docs/data.json
docs/files/src_Model.js.html
docs/files/src_Store.js.html
docs/files/src_decorators_attributes.js.html
docs/files/src_decorators_relationships.js.html
docs/files/src_schema.js.html
docs/files/src_utils.js.html
docs/index.html
package.json
spec/Model.spec.js
src/Model.js

I looked in both the mobile app and Portal and we only use lodash's `isEqual` method, even in `mobx-async-store` itself. I think it's confusing anyway to have a method with a name identical to another method that we also use frequently, if we were using it.

Remove our version of isEqual, it is not used [Ref #176874011]

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
docs/classes/Model.html
docs/classes/RelatedRecordsArray.html
docs/classes/Schema.html
docs/classes/Store.html
docs/data.json
docs/files/src_Model.js.html
docs/files/src_Store.js.html
docs/files/src_decorators_attributes.js.html
docs/files/src_decorators_relationships.js.html
docs/files/src_schema.js.html
docs/files/src_utils.js.html
docs/index.html
package.json
spec/Model.spec.js
src/decorators/relationships.js

currently, if there are any references to records in the `relationships` hash that are not loaded in the store, an attempt to `remove` *any* record that occurs after it in the `relatedRecordsArray` will cause an error.

fix removing related records when some not in store

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
package.json
spec/Store.spec.js
src/Store.js

We have a `loadingStates` property in the datastore, which is an observable `Map` object keyed by a query tag, and with values of sets of query information that is added and removed as fetches start / complete.
Previously, the `Map` and `Set` were initialized separately, with the `Set` initialized as a `shallow` observable so that its objects would not be observable, and thus would not be proxied objects and could be compared directly.
```js
Map() // observable
=> Set() // observable
=> Object() // not observable
```
However, because mobx propagates observability down, this seems to have broken after a recent change in a [mobx Typescript interceptor](https://github.com/mobxjs/mobx/pull/3180/files#diff-e26ca35ba470ffd74d1efb4a9f1a1b25d726f8b200b899d5e86764b20951b2f2R28-R29)
This PR changes …

fix loading states observables

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
package.json
spec/Store.spec.js
src/Store.js

If the same fetch params are used twice, the call is cached but the loadingState is attempted to delete twice.

add a warning for a double call

---

dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
package.json
spec/MockServer.spec.js
spec/utils.spec.js
src/MockServer.js
src/Store.js
src/utils.js

New configuration option to retry fetch attempts in the case of network failures.
When configuring the store, pass in `retryOptions` to `initializeNetworkConfiguration`
to set the number of total attempts and any delay between requests.
```
dataStore.initializeNetworkConfiguration({
retryOptions: {
attempts: 3,
delay: 1000,
}
})
```
`attempts`: The total number of attempts to make (default 1)
`delay`: Time to wait between failed attempts before retrying the request in milliseconds (default 0)

retry failed fetches

---

README.md
dist/mobx-async-store.cjs.js
dist/mobx-async-store.esm.js
package.json
spec/MockServer.spec.js
spec/Model.spec.js
spec/Store.spec.js
src/Model.js
src/Store.js
src/utils.js

Catch configured HTTP errors and reject updates to records with readable error messages.
This is a first approach to exposing the response status from Store fetches to the calling application.

configurable error messages
